### PR TITLE
New functions

### PR DESCRIPTION
**Pull request by KCNilssen**
Adds new function lookup_player()

If an exact matches are found for players with the same first and last name used in the search, it will output a list of those players found. This is useful for getting a players playerId number used in the mlb api

### CODE REVIEW

**Review by Mattsface — COMMENTED** [review]
So I have some thoughts! 

I haven't had a chance to go look at the statsapi, but instead of returning the entire JSON structure of a player(s). This function ONLY returns the Player ID(s)

**Comment by Mattsface** [comment]
I looked at the statsapi again. To continue on my above thoughts. Teams have IDs, and I'm guessing games also have IDs. We should have functions for looking up IDs when they are not present for players, games, and teams.

Thoughts?

**Comment by KCNilssen** [comment]
What do you mean by "functions for looking up IDs when they are not present for players, games, and teams"? 

We have a function for looking up live games, but that could be changed to two, where one is get_games_date, and the other is live_games that just calls get_games_date for todays date and such. 

Only issue with the just returning the ID's for the player is that if two players have the same name and play for different teams or what not, how will the user know what the id's they are receiving are?. Let me check if there are even players with the same name

**Comment by Mattsface** [comment]
It will be easier for me to show once I finish this example functions

**Comment by Mattsface** [comment]
Once my examples are finished, we will look into this!

Approving

**Pull request merged**
